name: screenshot_ntv
description: A Flutter plugin to take(support Platform Views) for Android and iOS with native code.
version: 1.0.1
homepage: https://github.com/n1kStas/ScreenshotNtv

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^14.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.n1k5tas.screenshot_ntv
        pluginClass: ScreenshotNtvPlugin
      ios:
        pluginClass: ScreenshotNtvPlugin